"""All data paths; set DATA_DIR to override ./data. See docs/01_data_sources.md."""
import os
import pathlib

REPO = pathlib.Path(__file__).resolve().parent
DATA_DIR = pathlib.Path(os.environ.get("DATA_DIR", REPO / "data"))
ARTIFACTS = REPO / "artifacts"
ARTIFACTS.mkdir(exist_ok=True)
HARMONISED_DIR = ARTIFACTS / "harmonised"
HARMONISED_DIR.mkdir(exist_ok=True)

# Raw datasets, plain standardised names (see docs/01_data_sources.md).
BER_CSV = DATA_DIR / "ber" / "building_energy_ratings.csv"
SAPS_CSV = DATA_DIR / "census" / "saps.csv"
SAPS_GPKG = DATA_DIR / "census" / "small_area_boundaries.gpkg"
JRC_XLSX = DATA_DIR / "curves" / "jrc_huizinga.xlsx"
MIDDLESEX_CSV = DATA_DIR / "curves" / "middlesex.csv"
DEM_TIF = DATA_DIR / "hazard" / "dem_dublin.tif"
COASTAL_TIF = DATA_DIR / "hazard" / "coastal_depth_rp100.tif"
FLUVIAL_DIR = DATA_DIR / "hazard" / "fluvial"
RAINFALL_TXT = DATA_DIR / "rainfall" / "met_eireann_rr.txt"

# Harmonised inputs (regenerated by src/00_harmonisation.py).
CURVE_FAMILY = HARMONISED_DIR / "reference_curve_family.csv"
EXPOSURE_PROFILES = HARMONISED_DIR / "irish_exposure_ber_profiles.csv"

# Print per-iteration boosting logs instead of the spinner (logging only).
VERBOSE_TRAINING = False
